[project]
name = "lygospy"
version = "0.1.0"
description = "A Python package for Lygos API"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jwt>=1.4.0",
    "requests>=2.32.5",
    "rich>=14.1.0",
]
